/**
 * This class is generated by jOOQ
 */
package top.zbeboy.fordownload.domain.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import top.zbeboy.fordownload.domain.tables.Address;
import top.zbeboy.fordownload.domain.tables.records.AddressRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressDao extends DAOImpl<AddressRecord, top.zbeboy.fordownload.domain.tables.pojos.Address, Integer> {

    /**
     * Create a new AddressDao without any configuration
     */
    public AddressDao() {
        super(Address.ADDRESS, top.zbeboy.fordownload.domain.tables.pojos.Address.class);
    }

    /**
     * Create a new AddressDao with an attached configuration
     */
    public AddressDao(Configuration configuration) {
        super(Address.ADDRESS, top.zbeboy.fordownload.domain.tables.pojos.Address.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(top.zbeboy.fordownload.domain.tables.pojos.Address object) {
        return object.getAddressid();
    }

    /**
     * Fetch records that have <code>addressID IN (values)</code>
     */
    public List<top.zbeboy.fordownload.domain.tables.pojos.Address> fetchByAddressid(Integer... values) {
        return fetch(Address.ADDRESS.ADDRESSID, values);
    }

    /**
     * Fetch a unique record that has <code>addressID = value</code>
     */
    public top.zbeboy.fordownload.domain.tables.pojos.Address fetchOneByAddressid(Integer value) {
        return fetchOne(Address.ADDRESS.ADDRESSID, value);
    }

    /**
     * Fetch records that have <code>city IN (values)</code>
     */
    public List<top.zbeboy.fordownload.domain.tables.pojos.Address> fetchByCity(String... values) {
        return fetch(Address.ADDRESS.CITY, values);
    }

    /**
     * Fetch records that have <code>street IN (values)</code>
     */
    public List<top.zbeboy.fordownload.domain.tables.pojos.Address> fetchByStreet(String... values) {
        return fetch(Address.ADDRESS.STREET, values);
    }

    /**
     * Fetch records that have <code>zip IN (values)</code>
     */
    public List<top.zbeboy.fordownload.domain.tables.pojos.Address> fetchByZip(String... values) {
        return fetch(Address.ADDRESS.ZIP, values);
    }
}
