/**
 * This class is generated by jOOQ
 */
package top.zbeboy.fordownload.domain;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import top.zbeboy.fordownload.domain.tables.Address;
import top.zbeboy.fordownload.domain.tables.SchemaVersion;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fordownload extends SchemaImpl {

    private static final long serialVersionUID = -1140979443;

    /**
     * The reference instance of <code>fordownload</code>
     */
    public static final Fordownload FORDOWNLOAD = new Fordownload();

    /**
     * The table <code>fordownload.address</code>.
     */
    public final Address ADDRESS = top.zbeboy.fordownload.domain.tables.Address.ADDRESS;

    /**
     * The table <code>fordownload.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = top.zbeboy.fordownload.domain.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * No further instances allowed
     */
    private Fordownload() {
        super("fordownload", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Address.ADDRESS,
            SchemaVersion.SCHEMA_VERSION);
    }
}
