/**
 * This class is generated by jOOQ
 */
package top.zbeboy.fordownload.domain;


import javax.annotation.Generated;

import top.zbeboy.fordownload.domain.tables.Address;
import top.zbeboy.fordownload.domain.tables.SchemaVersion;


/**
 * Convenience access to all tables in fordownload
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>fordownload.address</code>.
     */
    public static final Address ADDRESS = top.zbeboy.fordownload.domain.tables.Address.ADDRESS;

    /**
     * The table <code>fordownload.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = top.zbeboy.fordownload.domain.tables.SchemaVersion.SCHEMA_VERSION;
}
