/**
 * This class is generated by jOOQ
 */
package top.zbeboy.fordownload.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address implements Serializable {

    private static final long serialVersionUID = -1097037188;

    private Integer addressid;
    private String  city;
    private String  street;
    private String  zip;

    public Address() {}

    public Address(Address value) {
        this.addressid = value.addressid;
        this.city = value.city;
        this.street = value.street;
        this.zip = value.zip;
    }

    public Address(
        Integer addressid,
        String  city,
        String  street,
        String  zip
    ) {
        this.addressid = addressid;
        this.city = city;
        this.street = street;
        this.zip = zip;
    }

    public Integer getAddressid() {
        return this.addressid;
    }

    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getZip() {
        return this.zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address (");

        sb.append(addressid);
        sb.append(", ").append(city);
        sb.append(", ").append(street);
        sb.append(", ").append(zip);

        sb.append(")");
        return sb.toString();
    }
}
